swagger: "2.0"
info:
    title: User API
    description: API for user service.
    version: "1.0.0"
    contact:
        name: Hasibur Rahman
        email: your.email@example.com

paths:
    /register:
        post:
            summary: Register a new user
            description: This endpoint registers a new user with email, name, and password.
            tags:
                - User
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                  name: request body
                  description: The registration payload.
                  required: true
                  schema:
                    type: object
                    properties:
                        email:
                            type: string
                            example: "example@gmail.com"
                        name:
                            type: string
                            example: "john doe"
                        password:
                            type: string
                            example: "password"
                        role:
                            type: string
                            example: "admin"




            responses:
                "200":
                    description: User successfully registered
                    schema:
                        type: object
                        properties:
                            data:
                                type: object
                                properties:
                                    ID:
                                        type: integer
                                        example: 4
                                    CreatedAt:
                                        type: string
                                        example: "2024-12-05T15:30:11.5351903+06:00"
                                    UpdatedAt:
                                        type: string
                                        example: "2024-12-05T15:30:11.5351903+06:00"
                                    DeletedAt:
                                        type: string
                                        example: null
                                    Email:
                                        type: string
                                        example: "test1@gmail.com"
                                    Name:
                                        type: string
                                        example: "Hasib"
                                    Password:
                                        type: string
                                        example: "secret"
                "400":
                    description: Bad Request - Invalid input
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Invalid email format"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"

    /getUserByEmail:
        get:
            summary: Get user by email
            description: This endpoint retrieves a user by their email address.
            tags:
                - User
            parameters:
                - name: email
                  in: query
                  description: The email of the user to retrieve.
                  required: true
                  type: string
            responses:
                "200":
                    description: User successfully retrieved
                    schema:
                        type: object
                        properties:
                            data:
                                type: object
                                properties:
                                    ID:
                                        type: integer
                                        example: 1
                                    CreatedAt:
                                        type: string
                                        example: "0001-01-01T00:00:00Z"
                                    UpdatedAt:
                                        type: string
                                        example: "0001-01-01T00:00:00Z"
                                    DeletedAt:
                                        type: string
                                        example: null
                                    Email:
                                        type: string
                                        example: "hasibhr17@gmail.com"
                                    Name:
                                        type: string
                                        example: "Hasib"
                                    Password:
                                        type: string
                                        example: ""
                "400":
                    description: Bad Request - Invalid email format
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Invalid email format"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"

    /getAllUserEmails:
        get:
            summary: Get all user emails
            description: This endpoint retrieves a list of all user email addresses.
            tags:
                - User
            responses:
                "200":
                    description: List of user emails successfully retrieved
                    schema:
                        type: object
                        properties:
                            data:
                                type: array
                                items:
                                    type: string
                                    example: "hasibhr17@gmail.com"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"


    /subscribeToTopic:
        post:
            summary: Subscribe to a topic
            description: Subscribes a user to a specific topic.
            tags:
                - Subscription
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                  name: body
                  description: Request payload containing email and topic
                  required: true
                  schema:
                      type: object
                      properties:
                          email:
                              type: string
                              example: "test1@gmail.com"
                          topic:
                              type: string
                              example: "Sports"
            responses:
                "200":
                    description: Successfully subscribed to topic
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                                example: "successfully subscribed to topic"
                "400":
                    description: Bad Request - Invalid input
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Invalid request payload"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"

    /getSubscribedTopic/{user_id}:
        get:
            summary: Get subscribed topics for a user
            description: Retrieves a list of topics the user is subscribed to.
            tags:
                - Subscription
            parameters:
                - name: user_id
                  in: path
                  description: ID of the user whose subscribed topics are being fetched
                  required: true
                  type: integer
                  format: int32
            responses:
                "200":
                    description: List of subscribed topics
                    schema:
                        type: object
                        properties:
                            data:
                                type: array
                                items:
                                    type: string
                                example:
                                    - "Sports"
                                    - "Sports"
                                    - "Sports"
                                    - "Sports"
                                    - "Sports"
                                    - "Sports"
                                    - "Sports"
                                    - "Sports"
                "400":
                    description: Bad Request - Invalid user ID
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Invalid user id"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"

    /getSubscribedNews/{user_id}:
        get:
            summary: Get subscribed news for a user
            description: Retrieves news articles for topics the user is subscribed to.
            tags:
                - Subscription
            parameters:
                - name: user_id
                  in: path
                  description: ID of the user whose subscribed news articles are being fetched
                  required: true
                  type: integer
                  format: int32
            responses:
                "200":
                    description: List of subscribed news articles
                    schema:
                        type: object
                        properties:
                            data:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        news_id:
                                            type: integer
                                            example: 1
                                        title:
                                            type: string
                                            example: "A TV show about EA Sports' Madden games hits Prime Video on November 26"
                                        description:
                                            type: string
                                            example: "Madden NFL has been around for almost 40 years (really) so it’s high time the gaming franchise got the documentary treatment. Prime Video has got you covered."
                                        topic_name:
                                            type: string
                                            example: "Sports"
                                    example:
                                        - news_id: 1
                                          title: "A TV show about EA Sports' Madden games hits Prime Video on November 26"
                                          description: "Madden NFL has been around for almost 40 years (really) so it’s high time the gaming franchise got the documentary treatment. Prime Video has got you covered."
                                          topic_name: "Sports"
                                        - news_id: 2
                                          title: "Meta’s mixed-reality attempt at a Wii Sports knockoff is coming"
                                          description: "Home Sports is a cartoonist collection of games like bowling, badminton, and mini-golf, that can be played on Meta’s Quest 3 and 3S headsets."
                                          topic_name: "Sports"
                "400":
                    description: Bad Request - Invalid user ID
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Invalid user id"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"


    /sendEmails:
        post:
            summary: Send emails to all users
            description: Sends emails to all registered users.
            tags:
                - Email
            responses:
                "200":
                    description: Emails sent successfully
                    schema:
                        type: object
                        properties:
                            data:
                                type: string
                                example: "emails sent"
                "500":
                    description: Internal Server Error
                    schema:
                        type: object
                        properties:
                            error:
                                type: string
                                example: "Internal server error occurred"
